server.servlet.session.timeout=60m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none

paytm.mobile=9064341758
paytm.email=info.aaladin@gmail.com

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

logging.level.root=INFO
logging.file.name=logs/application.log