server:
  port: 80
  servlet:
    context-path: /
    session:
      cookie:
        same-site: none
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    password: tanmay@311
    url: jdbc:mysql://127.0.0.1:3306/easygofly
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
        globally-quoted-identifiers: true
        use-sql-comments: true
    show-sql: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant-path-matcher
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 640385530645-tm9e2fcnn119k38pr7ovuibab4fndbnq.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 1216865285686303
            client-secret: 7d899a7c513366f83cb64f496b8d03f1
            scope:
            - email
            - public_profile
           