logging:
  file:
    name: logs/application.log
  level:
    root: INFO
server:
  port: 444

  forward-headers-strategy: framework

  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
        same-site: none
        secure: true
      timeout: 60m
      tracking-modes: cookie
  ssl:
    enabled: false

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Rahul@311#
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/easygofly
    username: rahul
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
        globally-quoted-identifiers: true
        use-sql-comments: true
    show-sql: false
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
            client-id: 624963343127-vkeubt79bh4k0oo7me4fhgmp5lgh9q68.apps.googleusercontent.com
            client-secret: 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

